# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run: 
        working-directory: ./Code/educopter_frontend
    steps:
      - uses: actions/checkout@v3
      - name: Flutter action
        uses: subosito/flutter-action@v2.8.0
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build web

